repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.42.1
    hooks:
      - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main, --pattern, '\d\.\d\.\d']
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: circleci-validate
        name: circleci validate
        entry: circleci config validate
        language: system
        files: .circleci/config.yml

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
